import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'ru' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    myProfile: 'My Profile',
    edit: 'Edit',
    sagiDigitalCard: 'Sagi Digital Card',
    memberId: 'Member ID',
    barcode: 'Barcode',
    qrCode: 'QR Code',
    communities: 'Communities',
    partners: 'Partners',
    editProfile: 'Edit Profile',
    appearance: 'Appearance',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    notifications: 'Notifications',
    support: 'Support',
    language: 'Language',
    version: 'Version 1.0.0 • Made with Sagi Community',
    featuredOffers: 'Featured Offers',
    newOffers: 'New offers',
    myCommunities: 'My Communities',
    members: 'members',
    businesses: 'Businesses',
    offers: 'Offers',
    events: 'Events',
    searchOffers: 'Search offers...',
    all: 'All',
    food: 'Food',
    education: 'Education',
    beauty: 'Beauty',
    retail: 'Retail',
    thisCommunity: 'This Community',
    allNetwork: 'All Network',
    exclusive: 'Exclusive',
    active: 'Active',
    activeReward: 'Active Reward',
    validUntil: 'Valid until',
    howToRedeem: 'How to Redeem',
    redeemStep1: 'Show your Sagi Digital Card at checkout',
    redeemStep2: 'Staff will scan your QR code or barcode',
    redeemStep3: 'Discount will be applied automatically',
    redeemNow: 'Use Now',
    open: 'Open',
    myCard: 'My Profile',
    featured: 'Featured',
    new: 'New',
    discountDining: '20% off Dining',
    localBistro: 'Local Bistro',
    freeCoffee: 'Free Coffee',
    morningCafe: 'Morning Cafe',
    beautyServices: '15% Beauty Services',
    glowSpa: 'Glow Spa',
    downtownDistrict: 'Downtown District',
    techHub: 'Tech Hub',
    discountAllMeals: '20% off all meals',
    freeCoffeeWithPastry: 'Free coffee with any pastry',
    discountCourses: '10% off courses',
    gardenAcademy: 'Garden Academy',
    buy2Get1: 'Buy 2 Get 1 Free',
    styleBoutique: 'Style Boutique',
    mainStreet: '123 Main Street, Downtown District',
    openHours: 'Open: 11:00 AM - 10:00 PM',
    bistroDescription: 'A cozy neighborhood restaurant serving fresh, locally-sourced cuisine with a modern twist. Perfect for family dinners, business lunches, and special occasions.',
    validAllMenu: 'Valid on all menu items. Cannot be combined with other offers.',
    firstName: 'First Name',
    lastName: 'Last Name',
    birthday: 'Birthday',
    email: 'Email',
    phone: 'Phone',
    phoneNumber: 'Phone Number',
    changePhoto: 'Change Photo',
    save: 'Save',
    bio: 'Bio',
    bioPlaceholder: 'Tell something about yourself...',
    tags: 'Tags',
    tagsPlaceholder: 'Add a tag (e.g. Investor, Fintech)',
    addTag: 'Add',
    socialLinks: 'Social Links',
    linkedin: 'LinkedIn',
    instagram: 'Instagram',
    twitter: 'X (Twitter)',
    telegram: 'Telegram',
    website: 'Website',
    lightThemeDesc: 'Bright and clean interface',
    darkThemeDesc: 'Easy on the eyes, perfect for night',
    preview: 'Preview',
    languageChangeNote: 'Language changes will apply immediately across the entire app.',
    globalPushNotifications: 'Global Push Notifications',
    globalPushDesc: 'Receive all important updates',
    partnerOffers: 'New Partner Offers',
    partnerOffersDesc: 'Get notified about exclusive deals',
    communityUpdates: 'Sagi Community Updates',
    communityUpdatesDesc: 'News and announcements',
    notificationNote: 'You can manage notification permissions in your device settings.',
    contactUs: 'Contact Us',
    whatsappDesc: 'Chat with our support team',
    bot: 'Bot',
    telegramDesc: 'Get instant help via bot',
    callCenter: 'Call Center',
    callCenterDesc: 'Speak to a representative',
    faq: 'Frequently Asked Questions',
    faqQuestion1: 'How do I redeem my offers?',
    faqAnswer1: 'Simply show your Sagi Digital Card at checkout. The staff will scan your QR code or barcode to apply the discount automatically.',
    faqQuestion2: 'Can I use multiple offers at once?',
    faqAnswer2: 'Most offers cannot be combined with other promotions. Please check the specific offer details for more information.',
    faqQuestion3: 'How do I join a new community?',
    faqAnswer3: 'Contact your community administrator or use the invitation link provided by your organization to join a new Sagi community.',
    joinCommunity: 'Join Community',
    joinNewCommunity: 'Join New Community',
    showMoreCommunities: 'Show More Communities',
    enterAccessCode: 'Enter Community Access Code',
    searchCommunity: 'Search communities by name or ID',
    searchCommunityPlaceholder: 'Enter community name or ID...',
    searchResults: 'Search Results',
    noSearchResults: 'No communities found',
    scanQrInstead: 'Scan QR Code instead',
    verifyAndJoin: 'Verify & Join',
    suggestedCommunities: 'Suggested Communities for You',
    join: 'Join',
    joined: 'Joined',
    submitApplication: 'Submit Application',
    applicationPending: 'Application Pending',
    applicationSubmitted: 'Application Submitted',
    openToAll: 'Open to all professionals',
    verifying: 'Verifying...',
    successJoined: 'Successfully joined!',
    invalidCode: 'Invalid access code',
    communityDescription: 'A vibrant community for professionals',
    about: 'About',
    followUs: 'Follow Us',
    close: 'Close',
    users: 'Users',
    // Business role
    myBusiness: 'My Business',
    switchRole: 'Switch Role',
    activeOffers: 'Active Offers',
    redemptionsToday: 'Usage Today',
    membersReached: 'Members Reached',
    offersThisMonth: 'Offers This Month',
    recentRedemptions: 'Recent Usage',
    createNewOffer: 'Create New Offer',
    viewAnalytics: 'View Analytics',
    checkMemberAccess: 'Check Member Access',
    checkAccessDesc: 'Enter the member code or scan their QR to verify offer eligibility.',
    memberCodePlaceholder: 'Member code (e.g. 0042)',
    accessGranted: 'Access Granted',
    accessGrantedDesc: 'This member is eligible for the offer.',
    accessDenied: 'Access Denied',
    accessDeniedDesc: 'No valid membership found for this code.',
    showQRTitle: 'Show to Business',
    showQRDesc: 'Present this QR code at the counter to use your offer.',
    showQRHint: 'Keep screen brightness up',
    scanQR: 'Scan QR',
    typeCode: 'Type Code',
    scanQRHint: 'Point camera at member QR code',
    simulateScanValid: 'Simulate Valid',
    simulateScanInvalid: 'Simulate Invalid',
    memberCode: 'Member',
    scanAnother: 'Scan Another',
    submitUsage: 'Submit Usage',
    usageSubmitted: 'Usage Recorded',
    usageSubmittedDesc: 'Offer usage has been successfully recorded for this member.',
    myOffers: 'My Offers',
    noOffers: 'No offers yet',
    offerTitle: 'Offer Title',
    description: 'Description',
    category: 'Category',
    discount: 'Discount',
    termsConditions: 'Terms & Conditions',
    other: 'Other',
    offerTitlePlaceholder: 'e.g. 20% Off All Items',
    descriptionPlaceholder: 'Describe your offer...',
    discountPlaceholder: 'e.g. 20% off or Free coffee',
    termsPlaceholder: 'Enter any terms or conditions...',
    createOffer: 'Create Offer',
    newOffer: 'New Offer',
    businessProfile: 'Business Profile',
    offersCount: 'Offers',
    communitiesCount: 'Communities',
    contactInfo: 'Contact Info',
    dashboard: 'Dashboard',
    minAgo: 'min ago',
    hrAgo: 'hr ago',
    redemptionsCount: 'usage',
    usedOffer: 'used',
    // Admin role
    adminPanel: 'Admin Panel',
    totalCommunities: 'Total Communities',
    activeBusinesses: 'Active Businesses',
    totalMembers: 'Total Members',
    recentActivity: 'Recent Activity',
    actNewBusiness: 'New business joined AIFC',
    actOfferCreated: 'Offer created by Master Coffee',
    actUserJoined: 'User joined AIFC',
    actPendingApproval: 'Business pending approval: Bronx Fitness',
    actOfferRedeemed: 'Offer used at Hilton Astana',
    actNewUsers: '5 new users registered',
    timeMinAgo: 'min ago',
    monthJan: 'Jan', monthFeb: 'Feb', monthMar: 'Mar', monthApr: 'Apr',
    monthMay: 'May', monthJun: 'Jun', monthJul: 'Jul', monthAug: 'Aug',
    monthSep: 'Sep', monthOct: 'Oct', monthNov: 'Nov', monthDec: 'Dec',
    timeHrAgo: 'hr ago',
    quickLinks: 'Quick Links',
    manageCommunitiesDesc: 'Manage AIFC community',
    manageBusinessesDesc: 'Manage businesses',
    manageUsersDesc: 'Manage users',
    addCommunity: 'Add Community',
    communityName: 'Community Name',
    communityType: 'Type',
    addNew: 'Add',
    invite: 'Invite',
    invited: 'Invited',
    filterAll: 'All',
    filterPending: 'Pending',
    filterActive: 'Active',
    filterSuspended: 'Suspended',
    approve: 'Approve',
    reject: 'Reject',
    suspend: 'Suspend',
    restore: 'Restore',
    suspendUser: 'Suspend User',
    restoreUser: 'Restore User',
    memberSince: 'Member since',
    searchUsers: 'Search users...',
    searchBusinesses: 'Search businesses...',
    searchCommunities: 'Search communities...',
    communityDetails: 'Community Details',
    userDetails: 'User Details',
    recentRedemptionsCount: 'Total Usage',
    // Role Landing
    selectRole: 'Select your role',
    selectRoleDesc: "Choose how you'd like to use Sagi",
    roleUser: 'User',
    roleUserDesc: 'Explore offers from your communities',
    roleBusiness: 'Business',
    roleBusinessDesc: 'Manage your offers and analytics',
    roleAdmin: 'Admin',
    roleAdminDesc: 'Oversee the entire platform',
    switchRoleTitle: 'Switch Role',
    currentRole: 'Current',
    // Admin Analytics
    analytics: 'Analytics',
    businessAnalytics: 'Business Analytics',
    offerAnalytics: 'Offer Analytics',
    totalRedemptions: 'Total Usage',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',
    topBusinesses: 'Top Businesses',
    showAllBusinesses: 'Show all businesses',
    topOffers: 'Top Offers',
    redemptionsByDay: 'Usage by Day',
    conversionRate: 'Conversion Rate',
    avgPerBusiness: 'Avg per Business',
    viewDetails: 'View Details',
    backToAnalytics: 'Back to Analytics',
    offersActive: 'Active',
    offersPaused: 'Paused',
    redemptionsTotal: 'Total',
    joinedDate: 'Joined',
    businessName: 'Business',
    offerName: 'Offer',
    // Auth
    tagline: 'Your community loyalty app',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    orContinueWith: 'or continue with',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    sendSmsCode: 'Send SMS Code',
    verify: 'Verify',
    enterAccessCodeLogin: 'Enter your 6-digit access code',
    signInWithCode: 'Sign In with Code',
    forgotPassword: 'Forgot password?',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Repeat your password',
    joinWithCode: 'Join with Code',
    codePlaceholder: '_ _ _ _ _ _',
    signOut: 'Sign Out',
    switchRoleMenu: 'Switch Role',
    // Analytics — missing keys
    activeMembers: 'Active Members',
    topCategory: 'Top Category',
    memberEngagement: 'Member Engagement',
    viewedOffer: 'Viewed offer',
    redeemedOffer: 'Used offers',
    repeatRedeemersLabel: 'Reused offers',
    uniqueMembersLabel: 'unique members',
    communityEngagement: 'Community member engagement',
    membersUsedLabel: 'members used',
    ofTotal: 'of',
    cameBackLabel: 'came back',
    repeatVisitsLabel: 'repeat visits',
    totalUsesLabel: 'total uses',
    communityParticipation: 'Community participation',
    memberUsageByDay: 'Usage by day',
    howMembersUseOffers: 'How members use each offer',
    redemptionsLabel: 'usage',
    ofCommunityPct: 'of community',
    hideDetailsLabel: 'Hide details ▲',
    showMemberActivityLabel: 'Show member activity ▼',
    dailyRedemptionsByMembers: 'Daily usage by members',
    avgUsesPerMember: 'Avg uses per member',
    redemptionsByCommunity: 'Usage by Community',
    redemptionTimeline: 'Usage Timeline',
    dayMon: 'Mon', dayTue: 'Tue', dayWed: 'Wed', dayThu: 'Thu',
    dayFri: 'Fri', daySat: 'Sat', daySun: 'Sun',
    quickActions: 'Quick Actions',
    spaDaySpecial: 'Spa Day Special',
    offer15OffStay: '15% off stay',
    offer10OffStay: '10% off stay',
    offer10OffBev: '10% off beverages & food',
    offer10OffBevFull: '10% off beverages, food, accessories & coffee beans',
    offer10OffServices: '10% off services',
    offer10OffFood: '10% off food menu',
    offer10OffFoodBar: '10% off food and bar',
    offer10OffFoodDrinks: '10% off food and drinks',
    offer20OffBar: '20% off bar menu',
    offerGiftVouchers: 'Gift vouchers',
    offer15OffBestRate: '15% off best available rate',
    offer10OffBestRate: '10% off best available rate',
    offerCorporateRate: 'Corporate rate',
    offer10OffSpaRate: '10% off spa + 15% off rate & breakfast',
    offer15OffRateSpa: '15% off rate & 10% off spa',
    offer10OffTraining: '10% off training programmes',
    offer10OffTuition: '10% off tuition',
    offerDiscountEntrance: 'Discount on entrance fee',
    offer10to15OffDental: '10–15% off dental procedures',
    offerInsurancePackages: 'Insurance packages',
    offer20to30Off: '20–30% off',
    offer10OffRelocation: '10% off relocation & moving services',
    offer10Off: '10% off',
    offerSpecialMobilePackage: 'Special mobile package',
    offerCorporateDiscount: 'Corporate discount',
    hotel: 'Hotel',
    fitness: 'Fitness',
    healthcare: 'Health',
    travel: 'Travel',
    aifcName: 'AIFC',
    aifcDescription: 'The Astana International Financial Centre — a financial hub and special economic zone in Kazakhstan, open to foreign residents, investors, experts and expat families.',
    aifcVerified: 'Verified Member',
    residentId: 'Member ID',
    emeraldTier: 'Tier: Emerald Candidate',
    emeraldProgress: 'Emerald Status Progress',
    missionsCompleted: 'Missions Completed',
    activeMissions: 'Active Missions',
    mission1: 'Attend 2 AIFC Events',
    mission2: 'Visit 3 Exclusive Partners',
    missionDone: 'Done',
    missionPending: 'In Progress',
    upcomingEvents: 'Upcoming Events',
    rsvp: "I'm Going",
    rsvped: 'Going ✓',
    aifcExclusive: 'AIFC Exclusive',
    rsvpBoost: 'Event RSVP Active: +5% Boost',
    markAsRead: 'Mark as Read',
    communityNews: 'Community News',
    broadcastOnly: 'Broadcast only · No comments',
    react: 'React',
  },
  ru: {
    myProfile: 'Мой Профиль',
    edit: 'Изменить',
    sagiDigitalCard: 'Цифровая Карта Sagi',
    memberId: 'ID участника',
    barcode: 'Штрих-код',
    qrCode: 'QR-код',
    communities: 'Сообщества',
    partners: 'Партнеры',
    editProfile: 'Редактировать Профиль',
    appearance: 'Оформление',
    lightTheme: 'Светлая Тема',
    darkTheme: 'Темная Тема',
    notifications: 'Уведомления',
    support: 'Поддержка',
    language: 'Язык',
    version: 'Версия 1.0.0 • Создано с Sagi Community',
    featuredOffers: 'Избранные Предложения',
    newOffers: 'Новые предложения',
    myCommunities: 'Мои Сообщества',
    members: 'участников',
    businesses: 'Бизнесы',
    offers: 'Предложения',
    events: 'Мероприятия',
    searchOffers: 'Поиск предложений...',
    all: 'Все',
    food: 'Еда',
    education: 'Образование',
    beauty: 'Красота',
    retail: 'Магазины',
    thisCommunity: 'Это Сообщество',
    allNetwork: 'Вся Сеть',
    exclusive: 'Эксклюзив',
    active: 'Активно',
    activeReward: 'Активная Награда',
    validUntil: 'Действительно до',
    howToRedeem: 'Как Использовать',
    redeemStep1: 'Покажите вашу Цифровую Карту Sagi на кассе',
    redeemStep2: 'Персонал отсканирует ваш QR-код или штрих-код',
    redeemStep3: 'Скидка будет применена автоматически',
    redeemNow: 'Использовать Сейчас',
    open: 'Открыто',
    myCard: 'My Profile',
    featured: 'Избранное',
    new: 'Новое',
    discountDining: 'Скидка 20% на питание',
    localBistro: 'Местный Бистро',
    freeCoffee: 'Бесплатный кофе',
    morningCafe: 'Утреннее Кафе',
    beautyServices: 'Скидка 15% на услуги красоты',
    glowSpa: 'Glow Spa',
    downtownDistrict: 'Центральный Район',
    techHub: 'Технологический Хаб',
    discountAllMeals: 'Скидка 20% на все блюда',
    freeCoffeeWithPastry: 'Бесплатный кофе с выпечкой',
    discountCourses: 'Скидка 10% на курсы',
    gardenAcademy: 'Garden Academy',
    buy2Get1: 'Купи 2 получи 1 бесплатно',
    styleBoutique: 'Style Boutique',
    mainStreet: 'ул. Главная 123, Центральный Район',
    openHours: 'Открыто: 11:00 - 22:00',
    bistroDescription: 'Уютный районный ресторан, подающий свежую местную кухню с современным подходом. Идеально для семейных ужинов, деловых обедов и особых случаев.',
    validAllMenu: 'Действует на все позиции меню. Не суммируется с другими предложениями.',
    firstName: 'Имя',
    lastName: 'Фамилия',
    birthday: 'Дата рождения',
    email: 'Электронная почта',
    phone: 'Телефон',
    phoneNumber: 'Номер телефона',
    changePhoto: 'Изменить фото',
    save: 'Сохранить',
    bio: 'О себе',
    bioPlaceholder: 'Расскажите о себе...',
    tags: 'Теги',
    tagsPlaceholder: 'Добавить тег (напр. Инвестор, Финтех)',
    addTag: 'Добавить',
    socialLinks: 'Социальные сети',
    linkedin: 'LinkedIn',
    instagram: 'Instagram',
    twitter: 'X (Twitter)',
    telegram: 'Telegram',
    website: 'Веб-сайт',
    lightThemeDesc: 'Яркий и чистый интерфейс',
    darkThemeDesc: 'Не напрягает глаза, идеально для ночи',
    preview: 'Предпросмотр',
    languageChangeNote: 'Изменения языка применятся немедленно во всем приложении.',
    globalPushNotifications: 'Глобальные Push-уведомления',
    globalPushDesc: 'Получайте все важные обновления',
    partnerOffers: 'Новые предложения партнеров',
    partnerOffersDesc: 'Получайте уведомления об эксклюзивных предложениях',
    communityUpdates: 'Обновления Sagi Community',
    communityUpdatesDesc: 'Новости и объявления',
    notificationNote: 'Вы можете управлять разрешениями уведомлений в настройках устройства.',
    contactUs: 'Связаться с нами',
    whatsappDesc: 'Чат с нашей службой поддержки',
    bot: 'Бот',
    telegramDesc: 'Мгновенная помощь через бота',
    callCenter: 'Колл-центр',
    callCenterDesc: 'Поговорите с представителем',
    faq: 'Часто задаваемые вопросы',
    faqQuestion1: 'Как использовать мои предложения?',
    faqAnswer1: 'Просто покажите вашу Цифровую Карту Sagi на кассе. Персонал отсканирует ваш QR-код или штрих-код, чтобы автоматически применить скидку.',
    faqQuestion2: 'Могу ли я использовать несколько предложений одновременно?',
    faqAnswer2: 'Большинство предложений нельзя комбинировать с другими акциями. Пожалуйста, проверьте детали конкретного предложения для получения дополнительной информации.',
    faqQuestion3: 'Как присоединиться к новому сообществу?',
    faqAnswer3: 'Свяжитесь с администратором вашего сообщества или используйте пригласительную ссылку, предоставленную вашей организацией, чтобы присоединиться к новому сообществу Sagi.',
    joinCommunity: 'Присоединиться',
    joinNewCommunity: 'Вступить в сообщество',
    showMoreCommunities: 'Показать больше сообществ',
    enterAccessCode: 'Введите код доступа',
    searchCommunity: 'Поиск сообществ по названию или ID',
    searchCommunityPlaceholder: 'Введите название или ID сообщества...',
    searchResults: 'Результаты поиска',
    noSearchResults: 'Сообщества не найдены',
    scanQrInstead: 'Или отсканируйте QR',
    verifyAndJoin: 'Проверить и вступить',
    suggestedCommunities: 'Рекомендуемые сообщества',
    join: 'Вступить',
    joined: 'Вы вступили',
    submitApplication: 'Подать заявку',
    applicationPending: 'Заявка на рассмотрении',
    applicationSubmitted: 'Заявка подана',
    openToAll: 'Открыто для всех профессионалов',
    verifying: 'Проверка...',
    successJoined: 'Успешно вступили!',
    invalidCode: 'Неверный код доступа',
    communityDescription: 'Активное сообщество для профессионалов',
    about: 'О сообществе',
    followUs: 'Мы в соцсетях',
    close: 'Закрыть',
    users: 'Пользователи',
    // Business role
    myBusiness: 'Мой Бизнес',
    switchRole: 'Сменить роль',
    activeOffers: 'Активные предложения',
    redemptionsToday: 'Использовано сегодня',
    membersReached: 'Охвачено участников',
    offersThisMonth: 'Предложений в месяц',
    recentRedemptions: 'Последнее использование',
    createNewOffer: 'Создать предложение',
    viewAnalytics: 'Аналитика',
    checkMemberAccess: 'Проверить доступ',
    checkAccessDesc: 'Введите код участника или отсканируйте QR для проверки.',
    memberCodePlaceholder: 'Код участника (напр. 0042)',
    accessGranted: 'Доступ разрешён',
    accessGrantedDesc: 'Участник имеет право на предложение.',
    accessDenied: 'Доступ запрещён',
    accessDeniedDesc: 'Действительное членство не найдено.',
    showQRTitle: 'Показать бизнесу',
    showQRDesc: 'Предъявите этот QR-код на кассе для получения скидки.',
    showQRHint: 'Увеличьте яркость экрана',
    scanQR: 'Сканировать QR',
    typeCode: 'Ввести код',
    scanQRHint: 'Наведите камеру на QR-код участника',
    simulateScanValid: 'Симул. успешно',
    simulateScanInvalid: 'Симул. отказ',
    memberCode: 'Участник',
    scanAnother: 'Сканировать ещё',
    submitUsage: 'Подтвердить использование',
    usageSubmitted: 'Использование записано',
    usageSubmittedDesc: 'Использование предложения успешно записано.',
    myOffers: 'Мои предложения',
    noOffers: 'Нет предложений',
    offerTitle: 'Название предложения',
    description: 'Описание',
    category: 'Категория',
    discount: 'Скидка',
    termsConditions: 'Условия',
    other: 'Другое',
    offerTitlePlaceholder: 'напр. Скидка 20% на все товары',
    descriptionPlaceholder: 'Опишите ваше предложение...',
    discountPlaceholder: 'напр. Скидка 20% или Бесплатный кофе',
    termsPlaceholder: 'Введите условия...',
    createOffer: 'Создать предложение',
    newOffer: 'Новое предложение',
    businessProfile: 'Профиль бизнеса',
    offersCount: 'Предложения',
    communitiesCount: 'Сообщества',
    contactInfo: 'Контакты',
    dashboard: 'Панель',
    minAgo: 'мин назад',
    hrAgo: 'ч назад',
    redemptionsCount: 'использований',
    usedOffer: 'использовал',
    // Admin role
    adminPanel: 'Панель администратора',
    totalCommunities: 'Всего сообществ',
    activeBusinesses: 'Активных бизнесов',
    totalMembers: 'Всего участников',
    recentActivity: 'Последние действия',
    actNewBusiness: 'Новый бизнес присоединился к МФЦА',
    actOfferCreated: 'Предложение создано Master Coffee',
    actUserJoined: 'Пользователь присоединился к МФЦА',
    actPendingApproval: 'Бизнес ожидает подтверждения: Bronx Fitness',
    actOfferRedeemed: 'Предложение использовано в Hilton Astana',
    actNewUsers: '5 новых пользователей зарегистрировались',
    timeMinAgo: 'мин назад',
    monthJan: 'Янв', monthFeb: 'Фев', monthMar: 'Мар', monthApr: 'Апр',
    monthMay: 'Май', monthJun: 'Июн', monthJul: 'Июл', monthAug: 'Авг',
    monthSep: 'Сен', monthOct: 'Окт', monthNov: 'Ноя', monthDec: 'Дек',
    timeHrAgo: 'ч назад',
    quickLinks: 'Быстрые ссылки',
    manageCommunitiesDesc: 'Управление сообществом МФЦА',
    manageBusinessesDesc: 'Управление бизнесами',
    manageUsersDesc: 'Управление пользователями',
    addCommunity: 'Добавить сообщество',
    communityName: 'Название сообщества',
    communityType: 'Тип',
    addNew: 'Добавить',
    invite: 'Пригласить',
    invited: 'Приглашён',
    filterAll: 'Все',
    filterPending: 'Ожидающие',
    filterActive: 'Активные',
    filterSuspended: 'Заблокированные',
    approve: 'Одобрить',
    reject: 'Отклонить',
    suspend: 'Заблокировать',
    restore: 'Восстановить',
    suspendUser: 'Заблокировать',
    restoreUser: 'Восстановить',
    memberSince: 'Участник с',
    searchUsers: 'Поиск пользователей...',
    searchBusinesses: 'Поиск бизнесов...',
    searchCommunities: 'Поиск сообществ...',
    communityDetails: 'Детали сообщества',
    userDetails: 'Детали пользователя',
    recentRedemptionsCount: 'Всего использований',
    // Role Landing
    selectRole: 'Выберите роль',
    selectRoleDesc: 'Выберите как использовать Sagi',
    roleUser: 'Пользователь',
    roleUserDesc: 'Изучайте предложения сообществ',
    roleBusiness: 'Бизнес',
    roleBusinessDesc: 'Управляйте предложениями и аналитикой',
    roleAdmin: 'Администратор',
    roleAdminDesc: 'Управляйте всей платформой',
    switchRoleTitle: 'Сменить роль',
    currentRole: 'Текущая',
    // Admin Analytics
    analytics: 'Аналитика',
    businessAnalytics: 'Аналитика бизнеса',
    offerAnalytics: 'Аналитика предложений',
    totalRedemptions: 'Всего использований',
    thisWeek: 'Эта неделя',
    thisMonth: 'Этот месяц',
    allTime: 'Все время',
    topBusinesses: 'Топ бизнесов',
    showAllBusinesses: 'Показать все бизнесы',
    topOffers: 'Топ предложений',
    redemptionsByDay: 'Использование по дням',
    conversionRate: 'Конверсия',
    avgPerBusiness: 'Среднее на бизнес',
    viewDetails: 'Подробнее',
    backToAnalytics: 'К аналитике',
    offersActive: 'Активных',
    offersPaused: 'Приостановлен',
    redemptionsTotal: 'Всего',
    joinedDate: 'Вступил',
    businessName: 'Бизнес',
    offerName: 'Предложение',
    // Auth
    tagline: 'Приложение лояльности сообщества',
    signIn: 'Войти',
    createAccount: 'Создать аккаунт',
    orContinueWith: 'или продолжить с',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    dontHaveAccount: 'Нет аккаунта?',
    emailPlaceholder: 'Введите email',
    passwordPlaceholder: 'Введите пароль',
    sendSmsCode: 'Отправить SMS',
    verify: 'Подтвердить',
    enterAccessCodeLogin: 'Введите 6-значный код доступа',
    signInWithCode: 'Войти по коду',
    forgotPassword: 'Забыли пароль?',
    fullName: 'Полное имя',
    fullNamePlaceholder: 'Введите полное имя',
    confirmPassword: 'Подтвердите пароль',
    confirmPasswordPlaceholder: 'Повторите пароль',
    joinWithCode: 'Вступить по коду',
    codePlaceholder: '_ _ _ _ _ _',
    signOut: 'Выйти',
    switchRoleMenu: 'Сменить роль',
    // Analytics — missing keys
    activeMembers: 'Активные участники',
    topCategory: 'Топ категория',
    memberEngagement: 'Вовлеченность участников',
    viewedOffer: 'Просмотрели',
    redeemedOffer: 'Использовали',
    repeatRedeemersLabel: 'Повторно использовали',
    uniqueMembersLabel: 'уникальных участников',
    communityEngagement: 'Вовлеченность участников сообщества',
    membersUsedLabel: 'участников',
    ofTotal: 'из',
    cameBackLabel: 'вернулись',
    repeatVisitsLabel: 'повторные визиты',
    totalUsesLabel: 'всего использований',
    communityParticipation: 'Охват сообщества',
    memberUsageByDay: 'Использование по дням',
    howMembersUseOffers: 'Как участники используют предложения',
    redemptionsLabel: 'использований',
    ofCommunityPct: 'от сообщества',
    hideDetailsLabel: 'Скрыть ▲',
    showMemberActivityLabel: 'Активность участников ▼',
    dailyRedemptionsByMembers: 'Ежедневное использование участниками',
    avgUsesPerMember: 'Среднее на участника',
    redemptionsByCommunity: 'Использование по сообществам',
    redemptionTimeline: 'История использования',
    dayMon: 'Пн', dayTue: 'Вт', dayWed: 'Ср', dayThu: 'Чт',
    dayFri: 'Пт', daySat: 'Сб', daySun: 'Вс',
    quickActions: 'Быстрые действия',
    spaDaySpecial: 'Спа-день — спецпредложение',
    offer15OffStay: 'Скидка 15% на проживание',
    offer10OffStay: 'Скидка 10% на проживание',
    offer10OffBev: 'Скидка 10% на напитки и еду',
    offer10OffBevFull: 'Скидка 10% на напитки, еду, аксессуары и кофе',
    offer10OffServices: 'Скидка 10% на услуги',
    offer10OffFood: 'Скидка 10% на меню',
    offer10OffFoodBar: 'Скидка 10% на еду и бар',
    offer10OffFoodDrinks: 'Скидка 10% на еду и напитки',
    offer20OffBar: 'Скидка 20% на барное меню',
    offerGiftVouchers: 'Подарочные ваучеры',
    offer15OffBestRate: 'Скидка 15% на лучший тариф',
    offer10OffBestRate: 'Скидка 10% на лучший тариф',
    offerCorporateRate: 'Корпоративный тариф',
    offer10OffSpaRate: 'Скидка 10% на спа + 15% на тариф и завтрак',
    offer15OffRateSpa: 'Скидка 15% на номер и 10% на спа',
    offer10OffTraining: 'Скидка 10% на обучение',
    offer10OffTuition: 'Скидка 10% на обучение',
    offerDiscountEntrance: 'Скидка на вступительный взнос',
    offer10to15OffDental: 'Скидка 10–15% на стоматологию',
    offerInsurancePackages: 'Страховые пакеты',
    offer20to30Off: 'Скидка 20–30%',
    offer10OffRelocation: 'Скидка 10% на услуги релокации',
    offer10Off: 'Скидка 10%',
    offerSpecialMobilePackage: 'Специальный мобильный пакет',
    offerCorporateDiscount: 'Корпоративная скидка',
    hotel: 'Отель',
    fitness: 'Фитнес',
    healthcare: 'Здоровье',
    travel: 'Путешествия',
    aifcName: 'МФЦА',
    aifcDescription: 'Международный финансовый центр «Астана» — финансовый хаб и специальная экономическая зона Казахстана, открытая для иностранных резидентов, инвесторов, экспертов и семей экспатов.',
    aifcVerified: 'Verified Member',
    residentId: 'Member ID',
    emeraldTier: 'Tier: Emerald Candidate',
    emeraldProgress: 'Emerald Status Progress',
    missionsCompleted: 'Missions Completed',
    activeMissions: 'Active Missions',
    mission1: 'Attend 2 AIFC Events',
    mission2: 'Visit 3 Exclusive Partners',
    missionDone: 'Done',
    missionPending: 'In Progress',
    upcomingEvents: 'Upcoming Events',
    rsvp: "I'm Going",
    rsvped: 'Going ✓',
    aifcExclusive: 'AIFC Exclusive',
    rsvpBoost: 'Event RSVP Active: +5% Boost',
    markAsRead: 'Mark as Read',
    communityNews: 'Community News',
    broadcastOnly: 'Broadcast only · No comments',
    react: 'React',
  },
  kk: {
    myProfile: 'Менің Профилім',
    edit: 'Өзгерту',
    sagiDigitalCard: 'Sagi Цифрлық Картасы',
    memberId: 'Мүше ID',
    barcode: 'Штрих-код',
    qrCode: 'QR-код',
    communities: 'Қауымдастықтар',
    partners: 'Серіктестер',
    editProfile: 'Профильді Өңдеу',
    appearance: 'Көрініс',
    lightTheme: 'Ашық Тақырып',
    darkTheme: 'Қараңғы Тақырып',
    notifications: 'Хабарландырулар',
    support: 'Қолдау',
    language: 'Тіл',
    version: 'Нұсқа 1.0.0 • Sagi Community арқылы жасалған',
    featuredOffers: 'Таңдаулы Ұсыныстар',
    newOffers: 'Жаңа ұсыныстар',
    myCommunities: 'Менің Қауымдастықтарым',
    members: 'мүше',
    businesses: 'бизнес',
    offers: 'Ұсыныстар',
    events: 'Іс-шаралар',
    searchOffers: 'Ұсыныстарды іздеу...',
    all: 'Барлығы',
    food: 'Тамақ',
    education: 'Білім',
    beauty: 'Сұлулық',
    retail: 'Дүкендер',
    thisCommunity: 'Бұл Қауымдастық',
    allNetwork: 'Барлық Желі',
    exclusive: 'Эксклюзив',
    active: 'Белсенді',
    activeReward: 'Белсенді Сыйлық',
    validUntil: 'Жарамдылық мерзімі',
    howToRedeem: 'Қалай Пайдалану',
    redeemStep1: 'Sagi Цифрлық Картаңызды кассада көрсетіңіз',
    redeemStep2: 'Қызметкерлер сіздің QR-кодыңызды немесе штрих-кодыңызды сканерлейді',
    redeemStep3: 'Жеңілдік автоматты түрде қолданылады',
    redeemNow: 'Қазір Пайдалану',
    open: 'Ашық',
    myCard: 'My Profile',
    featured: 'Таңдаулы',
    new: 'Жаңа',
    discountDining: 'Тамаққа 20% жеңілдік',
    localBistro: 'Жергілікті Бистро',
    freeCoffee: 'Тегін Кофе',
    morningCafe: 'Таңғы Кафе',
    beautyServices: 'Сұлулық қызметтеріне 15% жеңілдік',
    glowSpa: 'Glow Spa',
    downtownDistrict: 'Орталық Аудан',
    techHub: 'Технологиялық Хаб',
    discountAllMeals: 'Барлық тағамдарға 20% жеңілдік',
    freeCoffeeWithPastry: 'Қамырдан жасалған өнімге тегін кофе',
    discountCourses: 'Курстарға 10% жеңілдік',
    gardenAcademy: 'Garden Academy',
    buy2Get1: '2 сатып ал 1 тегін ал',
    styleBoutique: 'Style Boutique',
    mainStreet: 'Басты көше 123, Орталық Аудан',
    openHours: 'Ашық: 11:00 - 22:00',
    bistroDescription: 'Жаңа тәсілмен жергілікті жаңа тағамдарды ұсынатын жайлы аудандық мейрамхана.',
    validAllMenu: 'Мәзірдің барлық позицияларына қолданылады. Басқа ұсыныстармен біріктірілмейді.',
    firstName: 'Аты',
    lastName: 'Тегі',
    birthday: 'Туған күні',
    email: 'Электрондық пошта',
    phone: 'Телефон',
    phoneNumber: 'Телефон нөмірі',
    changePhoto: 'Фотосуретті өзгерту',
    save: 'Сақтау',
    bio: 'Өзім туралы',
    bioPlaceholder: 'Өзіңіз туралы айтыңыз...',
    tags: 'Тегтер',
    tagsPlaceholder: 'Тег қосу (мыс. Инвестор, Финтех)',
    addTag: 'Қосу',
    socialLinks: 'Әлеуметтік желілер',
    linkedin: 'LinkedIn',
    instagram: 'Instagram',
    twitter: 'X (Twitter)',
    telegram: 'Telegram',
    website: 'Веб-сайт',
    lightThemeDesc: 'Жарқын және таза интерфейс',
    darkThemeDesc: 'Көзді жалықтырмайды, түнге өте қолайлы',
    preview: 'Алдын ала қарау',
    languageChangeNote: 'Тіл өзгерістері бүкіл қолданбада бірден қолданылады.',
    globalPushNotifications: 'Жалпы Push-хабарландырулар',
    globalPushDesc: 'Барлық маңызды жаңартуларды алыңыз',
    partnerOffers: 'Серіктестердің жаңа ұсыныстары',
    partnerOffersDesc: 'Эксклюзивті ұсыныстар туралы хабарландырулар алыңыз',
    communityUpdates: 'Sagi Community жаңартулары',
    communityUpdatesDesc: 'Жаңалықтар және хабарландырулар',
    notificationNote: 'Хабарландыру рұқсаттарын құрылғы параметрлерінде басқаруға болады.',
    contactUs: 'Бізбен байланысыңыз',
    whatsappDesc: 'Қолдау қызметімізбен сөйлесіңіз',
    bot: 'Бот',
    telegramDesc: 'Бот арқылы лезде көмек алыңыз',
    callCenter: 'Қоңырау орталығы',
    callCenterDesc: 'Өкілмен сөйлесіңіз',
    faq: 'Жиі қойылатын сұрақтар',
    faqQuestion1: 'Ұсыныстарымды қалай пайдалануға болады?',
    faqAnswer1: 'Sagi Цифрлық Картаңызды кассада көрсетіңіз. Қызметкерлер жеңілдікті автоматты түрде қолдану үшін QR-кодыңызды немесе штрих-кодыңызды сканерлейді.',
    faqQuestion2: 'Бірнеше ұсынысты бір мезгілде пайдалануға бола ма?',
    faqAnswer2: 'Көптеген ұсыныстарды басқа акциялармен біріктіруге болмайды. Қосымша ақпарат алу үшін нақты ұсыныс мәліметтерін тексеріңіз.',
    faqQuestion3: 'Жаңа қауымдастыққа қалай қосылуға болады?',
    faqAnswer3: 'Жаңа Sagi қауымдастығына қосылу үшін қауымдастық әкімшісімен байланысыңыз немесе ұйымыңыз ұсынған шақыру сілтемесін пайдаланыңыз.',
    joinCommunity: 'Қосылу',
    joinNewCommunity: 'Жаңа қауымдастыққа қосылу',
    showMoreCommunities: 'Көбірек қауымдастықтар',
    enterAccessCode: 'Қолжетімділік кодын енгізіңіз',
    searchCommunity: 'Атауы немесе ID бойынша қауымдастық іздеу',
    searchCommunityPlaceholder: 'Қауымдастық атауын немесе ID енгізіңіз...',
    searchResults: 'Іздеу нәтижелері',
    noSearchResults: 'Қауымдастықтар табылмады',
    scanQrInstead: 'Немесе QR-кодты сканерлеңіз',
    verifyAndJoin: 'Тексеру және қосылу',
    suggestedCommunities: 'Ұсынылатын қауымдастықтар',
    join: 'Қосылу',
    joined: 'Қосылдыңыз',
    submitApplication: 'Өтінім беру',
    applicationPending: 'Өтінім қаралуда',
    applicationSubmitted: 'Өтінім жіберілді',
    openToAll: 'Барлық мамандарға ашық',
    verifying: 'Тексеру...',
    successJoined: 'Сәтті қосылдыңыз!',
    invalidCode: 'Жарамсыз қолжетімділік коды',
    communityDescription: 'Мамандарға арналған белсенді қауымдастық',
    about: 'Қауымдастық туралы',
    followUs: 'Біз әлеуметтік желілерде',
    close: 'Жабу',
    users: 'Пайдаланушылар',
    // Business role
    myBusiness: 'Менің Бизнесім',
    switchRole: 'Рөлді ауыстыру',
    activeOffers: 'Белсенді ұсыныстар',
    redemptionsToday: 'Бүгінгі өтеулер',
    membersReached: 'Қамтылған мүшелер',
    offersThisMonth: 'Осы айдағы ұсыныстар',
    recentRedemptions: 'Соңғы өтеулер',
    createNewOffer: 'Жаңа ұсыныс жасау',
    viewAnalytics: 'Аналитика',
    checkMemberAccess: 'Қолжетімділікті тексеру',
    checkAccessDesc: 'Мүше кодын енгізіңіз немесе QR сканерлеңіз.',
    memberCodePlaceholder: 'Мүше коды (мыс. 0042)',
    accessGranted: 'Қолжетімділік берілді',
    accessGrantedDesc: 'Бұл мүше ұсынысқа қатыса алады.',
    accessDenied: 'Қолжетімділік жоқ',
    accessDeniedDesc: 'Жарамды мүшелік табылмады.',
    showQRTitle: 'Бизнеске көрсету',
    showQRDesc: 'Жеңілдік алу үшін QR кодты кассада көрсетіңіз.',
    showQRHint: 'Экран жарықтығын арттырыңыз',
    scanQR: 'QR сканерлеу',
    typeCode: 'Код енгізу',
    scanQRHint: 'Камераны мүше QR кодына бағыттаңыз',
    simulateScanValid: 'Жарамды симуляция',
    simulateScanInvalid: 'Жарамсыз симуляция',
    memberCode: 'Мүше',
    scanAnother: 'Тағы сканерлеу',
    submitUsage: 'Пайдалануды растау',
    usageSubmitted: 'Пайдалану тіркелді',
    usageSubmittedDesc: 'Мүшенің ұсынысты пайдалануы сәтті тіркелді.',
    myOffers: 'Менің ұсыныстарым',
    noOffers: 'Ұсыныстар жоқ',
    offerTitle: 'Ұсыныс атауы',
    description: 'Сипаттама',
    category: 'Санат',
    discount: 'Жеңілдік',
    termsConditions: 'Шарттар',
    other: 'Басқа',
    offerTitlePlaceholder: 'мыс. Барлық тауарларға 20% жеңілдік',
    descriptionPlaceholder: 'Ұсынысыңызды сипаттаңыз...',
    discountPlaceholder: 'мыс. 20% жеңілдік немесе тегін кофе',
    termsPlaceholder: 'Шарттарды енгізіңіз...',
    createOffer: 'Ұсыныс жасау',
    newOffer: 'Жаңа ұсыныс',
    businessProfile: 'Бизнес профилі',
    offersCount: 'Ұсыныстар',
    communitiesCount: 'Қауымдастықтар',
    contactInfo: 'Байланыс',
    dashboard: 'Бақылау тақтасы',
    minAgo: 'мин бұрын',
    hrAgo: 'сағ бұрын',
    redemptionsCount: 'өтеу',
    usedOffer: 'пайдаланды',
    // Admin role
    adminPanel: 'Әкімші тақтасы',
    totalCommunities: 'Барлық қауымдастықтар',
    activeBusinesses: 'Белсенді бизнестер',
    totalMembers: 'Барлық мүшелер',
    recentActivity: 'Соңғы әрекеттер',
    actNewBusiness: 'Жаңа бизнес ХҚКО-ға қосылды',
    actOfferCreated: 'Master Coffee ұсыныс жасады',
    actUserJoined: 'Пайдаланушы ХҚКО-ға қосылды',
    actPendingApproval: 'Бизнес бекітуді күтуде: Bronx Fitness',
    actOfferRedeemed: 'Ұсыныс Hilton Astana-да пайдаланылды',
    actNewUsers: '5 жаңа пайдаланушы тіркелді',
    timeMinAgo: 'мин бұрын',
    monthJan: 'Қаң', monthFeb: 'Ақп', monthMar: 'Нау', monthApr: 'Сәу',
    monthMay: 'Мам', monthJun: 'Мау', monthJul: 'Шіл', monthAug: 'Там',
    monthSep: 'Қыр', monthOct: 'Қаз', monthNov: 'Қар', monthDec: 'Жел',
    timeHrAgo: 'сағ бұрын',
    quickLinks: 'Жылдам сілтемелер',
    manageCommunitiesDesc: 'ХҚКО қауымдастығын басқару',
    manageBusinessesDesc: 'Бизнестерді басқару',
    manageUsersDesc: 'Пайдаланушыларды басқару',
    addCommunity: 'Қауымдастық қосу',
    communityName: 'Қауымдастық атауы',
    communityType: 'Түрі',
    addNew: 'Қосу',
    invite: 'Шақыру',
    invited: 'Шақырылған',
    filterAll: 'Барлығы',
    filterPending: 'Күтілуде',
    filterActive: 'Белсенді',
    filterSuspended: 'Блокталған',
    approve: 'Мақұлдау',
    reject: 'Қабылдамау',
    suspend: 'Блоктау',
    restore: 'Қалпына келтіру',
    suspendUser: 'Блоктау',
    restoreUser: 'Қалпына келтіру',
    memberSince: 'Мүше болған',
    searchUsers: 'Пайдаланушыларды іздеу...',
    searchBusinesses: 'Бизнестерді іздеу...',
    searchCommunities: 'Қауымдастықтарды іздеу...',
    communityDetails: 'Қауымдастық мәліметтері',
    userDetails: 'Пайдаланушы мәліметтері',
    recentRedemptionsCount: 'Барлық өтеулер',
    // Role Landing
    selectRole: 'Рөліңізді таңдаңыз',
    selectRoleDesc: 'Sagi қолдану тәсілін таңдаңыз',
    roleUser: 'Пайдаланушы',
    roleUserDesc: 'Қауымдастықтардың ұсыныстарын зерттеңіз',
    roleBusiness: 'Бизнес',
    roleBusinessDesc: 'Ұсыныстарыңызды басқарыңыз',
    roleAdmin: 'Әкімші',
    roleAdminDesc: 'Бүкіл платформаны басқарыңыз',
    switchRoleTitle: 'Рөлді ауыстыру',
    currentRole: 'Ағымдағы',
    // Admin Analytics
    analytics: 'Аналитика',
    businessAnalytics: 'Бизнес аналитикасы',
    offerAnalytics: 'Ұсыныс аналитикасы',
    totalRedemptions: 'Барлық өтеулер',
    thisWeek: 'Осы апта',
    thisMonth: 'Осы ай',
    allTime: 'Барлық уақыт',
    topBusinesses: 'Үздік бизнестер',
    showAllBusinesses: 'Барлық бизнестерді көрсету',
    topOffers: 'Үздік ұсыныстар',
    redemptionsByDay: 'Күн бойынша өтеулер',
    conversionRate: 'Конверсия',
    avgPerBusiness: 'Бизнес бойынша орта',
    viewDetails: 'Толығырақ',
    backToAnalytics: 'Аналитикаға',
    offersActive: 'Белсенді',
    offersPaused: 'Тоқтатылған',
    redemptionsTotal: 'Барлығы',
    joinedDate: 'Қосылды',
    businessName: 'Бизнес',
    offerName: 'Ұсыныс',
    // Auth
    tagline: 'Қауымдастық адалдық қолданбасы',
    signIn: 'Кіру',
    createAccount: 'Аккаунт жасау',
    orContinueWith: 'немесе жалғастыру',
    alreadyHaveAccount: 'Аккаунт бар ма?',
    dontHaveAccount: 'Аккаунт жоқ па?',
    emailPlaceholder: 'Email енгізіңіз',
    passwordPlaceholder: 'Құпия сөз енгізіңіз',
    sendSmsCode: 'SMS жіберу',
    verify: 'Растау',
    enterAccessCodeLogin: '6 таңбалы кодты енгізіңіз',
    signInWithCode: 'Кодпен кіру',
    forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
    fullName: 'Толық аты',
    fullNamePlaceholder: 'Толық атыңызды енгізіңіз',
    confirmPassword: 'Құпия сөзді растаңыз',
    confirmPasswordPlaceholder: 'Құпия сөзді қайталаңыз',
    joinWithCode: 'Кодпен қосылу',
    codePlaceholder: '_ _ _ _ _ _',
    signOut: 'Шығу',
    switchRoleMenu: 'Рөлді ауыстыру',
    // Analytics — missing keys
    activeMembers: 'Белсенді мүшелер',
    topCategory: 'Үздік санат',
    memberEngagement: 'Мүшелер белсенділігі',
    viewedOffer: 'Қарады',
    redeemedOffer: 'Пайдаланды',
    repeatRedeemersLabel: 'Қайтадан келді',
    uniqueMembersLabel: 'бірегей мүшелер',
    communityEngagement: 'Қауымдастық мүшелерінің белсенділігі',
    membersUsedLabel: 'мүшелер',
    ofTotal: 'ішінен',
    cameBackLabel: 'қайтып келді',
    repeatVisitsLabel: 'қайта кіру',
    totalUsesLabel: 'барлық пайдалану',
    communityParticipation: 'Қауымдастық қамтуы',
    memberUsageByDay: 'Күн бойынша пайдалану',
    howMembersUseOffers: 'Мүшелер ұсыныстарды қалай пайдаланады',
    redemptionsLabel: 'өтеу',
    ofCommunityPct: 'қауымдастықтан',
    hideDetailsLabel: 'Жасыру ▲',
    showMemberActivityLabel: 'Белсенділікті көрсету ▼',
    dailyRedemptionsByMembers: 'Мүшелердің күнделікті өтеулері',
    avgUsesPerMember: 'Мүшеге орташа',
    redemptionsByCommunity: 'Қауымдастықтар бойынша өтеулер',
    redemptionTimeline: 'Өтеу тарихы',
    dayMon: 'Дс', dayTue: 'Сс', dayWed: 'Ср', dayThu: 'Бс',
    dayFri: 'Жм', daySat: 'Сн', daySun: 'Жк',
    quickActions: 'Жылдам әрекеттер',
    spaDaySpecial: 'Спа-күн арнайы ұсыныс',
    offer15OffStay: 'Тұруға 15% жеңілдік',
    offer10OffStay: 'Тұруға 10% жеңілдік',
    offer10OffBev: 'Сусындар мен тағамға 10% жеңілдік',
    offer10OffBevFull: 'Сусындарға, тағамға, аксессуарларға және кофеге 10% жеңілдік',
    offer10OffServices: 'Қызметтерге 10% жеңілдік',
    offer10OffFood: 'Менюге 10% жеңілдік',
    offer10OffFoodBar: 'Тағам мен барға 10% жеңілдік',
    offer10OffFoodDrinks: 'Тағам мен сусындарға 10% жеңілдік',
    offer20OffBar: 'Бар менюіне 20% жеңілдік',
    offerGiftVouchers: 'Сыйлық ваучерлері',
    offer15OffBestRate: 'Ең жақсы тарифке 15% жеңілдік',
    offer10OffBestRate: 'Ең жақсы тарифке 10% жеңілдік',
    offerCorporateRate: 'Корпоративтік тариф',
    offer10OffSpaRate: 'Спаға 10% + тариф пен таңертеңгілікке 15% жеңілдік',
    offer15OffRateSpa: 'Бөлмеге 15% және спаға 10% жеңілдік',
    offer10OffTraining: 'Оқуға 10% жеңілдік',
    offer10OffTuition: 'Оқу ақысына 10% жеңілдік',
    offerDiscountEntrance: 'Кіру жарнасына жеңілдік',
    offer10to15OffDental: 'Стоматологияға 10–15% жеңілдік',
    offerInsurancePackages: 'Сақтандыру бумалары',
    offer20to30Off: '20–30% жеңілдік',
    offer10OffRelocation: 'Көшу қызметтеріне 10% жеңілдік',
    offer10Off: '10% жеңілдік',
    offerSpecialMobilePackage: 'Арнайы мобильдік пакет',
    offerCorporateDiscount: 'Корпоративтік жеңілдік',
    hotel: 'Қонақ үй',
    fitness: 'Фитнес',
    healthcare: 'Денсаулық',
    travel: 'Саяхат',
    aifcName: 'ХҚКО',
    aifcDescription: 'Астана халықаралық қаржы орталығы — Қазақстандағы қаржы хабы және арнайы экономикалық аймақ, шетелдік резиденттерге, инвесторларға, сарапшыларға және эспат отбасыларына ашық.',
    aifcVerified: 'Verified Member',
    residentId: 'Member ID',
    emeraldTier: 'Tier: Emerald Candidate',
    emeraldProgress: 'Emerald Status Progress',
    missionsCompleted: 'Missions Completed',
    activeMissions: 'Active Missions',
    mission1: 'Attend 2 AIFC Events',
    mission2: 'Visit 3 Exclusive Partners',
    missionDone: 'Done',
    missionPending: 'In Progress',
    upcomingEvents: 'Upcoming Events',
    rsvp: "I'm Going",
    rsvped: 'Going ✓',
    aifcExclusive: 'AIFC Exclusive',
    rsvpBoost: 'Event RSVP Active: +5% Boost',
    markAsRead: 'Mark as Read',
    communityNews: 'Community News',
    broadcastOnly: 'Broadcast only · No comments',
    react: 'React',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sagi-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('sagi-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
